W10D1/music_app/config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new, :create]
  end
  resources :albums, only: [:edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
end

W10D1/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  album_type :string           not null
#

class Album < ApplicationRecord
  validates :title, :year, presence: true
  validates :album_type, inclusion: ["Studio", "Live"]

  belongs_to :band
  has_many :tracks,
    dependent: :destroy

  def band_name
    band.name
  end

end

W10D1/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
  has_many :albums
end

W10D1/music_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint           not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  ord        :integer          not null
#  lyrics     :text
#  track_type :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :ord, presence: true
  validates :title, uniqueness: {scope: :album_id}
  validates :track_type, inclusion: ["Regular","Bonus"]

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band
    
end

W10D1/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6}
  before_validation :ensure_session_token
  
  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token! 
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def is_password?(password)
    bcrypt_password = BCrypt::Password.new(self.password_digest)
    bcrypt_password.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

W10D1/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user

  def new 
    @bands = Band.all
    @album = Album.new
  end

  def create
    @bands = Band.all

    @album = Album.new(album_params)
    if @album.save
      flash[:success] = ["Cool, we've added it to our library!"]
      redirect_to album_url(@album)
    else 
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])
    render :edit
  end

  def update 
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      flash[:success] = "Album updated! Thanks for your help"
      redirect_to album_url(@album)
    else
      flash.now[:errors]
      render :edit
    end
  end

  def destroy 
    album = Album.find(params[:id])
    band = album.band
    album.destroy!
    redirect_to band_url(band)
  end


  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :album_type)
  end
  
end

W10D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in? 
    !!current_user
  end

  def log_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def log_out 
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end

  def require_user
    redirect_to new_session_url unless logged_in?
  end
end

W10D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user
  
  def index
    @bands = Band.all
  end

  def show 
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create 
    @band = Band.new(band_params)
    if @band.save 
      redirect_to band_url(@band)
    else 
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update 
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy 
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

W10D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    render :new
  end

  def create 
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      log_in(user)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Invalid login credentials"]
      render :new
    end
  end

  def destroy 
    log_out
    flash[:success] = ["Logged out! See you soon!"]
    redirect_to new_session_url
  end 
  
end

W10D1/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user

  def new
    @track = Track.new
    @albums = Album.all
  end

  def create
    @albums = Album.all
    @track = Track.new(track_params)
    if @track.save 
      flash[:success] = ["Track saved"]
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @albums = Album.all
    @track = Track.find(params[:id])
  end

  def update 
    @albums = Album.all
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def show 
    @track = Track.find(params[:id])
  end

  def destroy
    track = Track.find(params[:id])
    album = track.album
    track.destroy!
    redirect_to album_url(album)
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :title, :ord, :lyrics, :track_type)
  end
end

W10D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show 
    render :show
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W10D1/music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
    <input
        type="hidden"
        name="authenticity_token"
        value="#{form_authenticity_token}"/>
    HTML
  end
end

W10D1/music_app/app/views/albums/edit.html.erb
<h1> Edit an album </h1>

<form action="<%=album_url%>" method="post">
<input type="hidden" name="_method" value="patch"/>

  <label>Band
    <select name="album[band_id]">
      <option value="<%=@album.band_id%>"><%= @album.band_name %></option>
      <%@bands.each do |band|%>
        <option value="<%=band.id%>"> <%= band.name %></option>
      <%end%>
    </select>
  </label>

  <label>Title 
    <input type="text" name="album[title]" value="<%=@album.title%>"/>
  </label>

  <label>Year
    <input type="number" name="album[year]" value ="<%=@album.year%>"/>
  </label>

  <label>Album Type 
    <input
      type="radio"
      name="album[album_type]"
      value="Studio"
      id="studio_album"
      <%= @album.album_type == "Studio" ? "checked" : "" %> 
    />
    <label for="studio_album">Studio</label>
    <input
      type="radio"
      name="album[album_type]"
      value="Live"
      id="live_album"
      <%= @album.album_type == "Live" ? "checked" : "" %>
    />
    <label for="live_album">Live</label>
  </label>

  <input type="submit" value="Submit the album">

</form>

W10D1/music_app/app/views/albums/new.html.erb
<h1> Submit an album </h1>

<form action="<%=band_albums_url%>" method="post">

  <label>Band
    <select name="album[band_id]">
      <option> ---- </option>
      <%@bands.each do |band|%>
        <option value="<%=band.id%>"> <%= band.name %></option>
      <%end%>
    </select>
  </label>

  <label>Title 
    <input type="text" name="album[title]"/>
  </label>

  <label>Year
    <input type="number" name="album[year]"/>
  </label>

  <label>Album Type 
    <input
      type="radio"
      name="album[album_type]"
      value="Studio"
      id="studio_album" />
    <label for="studio_album">Studio</label>
    <input
      type="radio"
      name="album[album_type]"
      value="Live"
      id="live_album" />
    <label for="live_album">Live</label>
  </label>

  <input type="submit" value="Submit the album">

</form>

W10D1/music_app/app/views/albums/show.html.erb
<h1> <%=@album.title%> </h1>

<div>
  <a href="<%=edit_album_url(@album)%>">Fix it! | </a>
  <a href="<%=new_album_track_url(@album)%>">Add a track!</a>
</div>
</br>
<div>
  Album Info:
  <table> 
      <tr>
        <th>Attribute</th>
        <th>Value</th>
      </tr>
      <% [:band_name, :year, :album_type].each do |attr_name| %>
        <tr>
          <td><%= attr_name %></td>
          <td><%= @album.send(attr_name) %></td>
        </tr>
      <% end %>
  </table>
  </br>
  Track Info:
  <table>
    <tr>
      <th> </th>
      <th>Song Title</th>
    </tr>
    <%@album.tracks.each do |track|%>
      <tr>
        <td><%=track.ord%></td>
        <td><a href="<%=track_url(track)%>"><%=track.title%></a></td>
      </tr>
    <%end%>
  </table>
</div>
</br>
  <form action="<%= album_url %>" method="POST">
    <input type="hidden" name="_method" value="DELETE" />
    <input type="submit" value="Delele this album?">
  </form>
</br>

<a href="<%=band_url(@album.band.id)%>">back to <%=@album.band_name%>?</a>

W10D1/music_app/app/views/bands/index.html.erb
<h1>All the bands</h1>
<%@bands.each do |band|%>
  <a href="<%=band_url(band)%>"> <%= band.name %></a> </br>
<%end%>
</br>
<a href="<%=new_band_url%>"> Submit a band? </a> 
</br>

W10D1/music_app/app/views/bands/new.html.erb
<h1> Submit a band! </h1>

<form action="<%= bands_url %>" method="post">
  <label> Band name:
    <input type="text" name="band[name]">
    <input type="submit" value="Submit your band">
  </label>
</form>

W10D1/music_app/app/views/bands/show.html.erb
<h1> <%=@band.name%> </h1>

<% if @band.albums.empty? %>
  <p> No albums yet. Help us improve our library! </p>
<%else%>
  <div>
    <table>
      <tr><th>Albums</th></tr>
      <%@band.albums.each do |album|%>
        <td> <a href="<%=album_url(album)%>"> <%=album.title%> </a> </td>
        <%end%>
    </table>
  </div>
  </br>
<%end%>

<a href="<%=new_band_album_url(@band)%>"> Submit an album? </a>
</br>
<a href="<%=bands_url%>"> Back to all bands? </a>

W10D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <link href="https://fonts.google.com/?selection.family=Manjari" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
    <div align="right">
      <% if logged_in? %>
        Hey there, <%= current_user.email %>!
        <form action="<%=session_url%>" method="post">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%=form_authenticity_token%>"/>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="log out?">
        </form>
      <% else %>
        <a href="<%= new_session_url %>">Log In | </a>
        <a href="<%= new_user_url%>">Sign Up Now</a>
      <% end %>
    </div>
   <h1>Music App</h1> 

    <%=flash[:errors]%>
    <%= yield %>
  </body>
</html>

W10D1/music_app/app/views/tracks/edit.html.erb
<h1> Edit a track</h1>

<form action="<%=track_url%>" method="post">
  <input type="hidden" name="_method" value="patch">

  <label>Album
    <select name="track[album_id]">
      <option value="<%@track.album.id%>"> <%=@track.album.title%> </option>
      <%@albums.each do |album|%>
      <%next if album == @track.album%>
        <option value="<%=album.id%>"> <%= album.title %></option>
      <%end%>
    </select>
  </label>

  <label>Title 
    <input type="text" name="track[title]" value=<%=@track.title%>/>
  </label>

  <label>Track Number
    <input type="number" name="track[ord]" value=<%=@track.ord%>/>
  </label>

  <label>Track Type 
    <input
      type="radio"
      name="track[track_type]"
      value="Regular"
      id="reg_track" 
      <%= @track.track_type == "Regular" ? "checked" : "" %> 
      />
    <label for="reg_track">Regular</label>
    <input
      type="radio"
      name="track[track_type]"
      value="Bonus"
      id="bonus_track" 
      <%= @track.track_type == "Bonus" ? "checked" : "" %> 
      />
    <label for="bonus_track">Bonus</label>
  </label>
  </br>
  <label>Lyrics
    <textarea name="track[lyrics]"></textarea>
  </label>
  <input type="submit" value="Submit the track">

</form>

W10D1/music_app/app/views/tracks/new.html.erb
<h1> Submit a track</h1>

<form action="<%=tracks_url%>" method="post">

  <label>Album
    <select name="track[album_id]">
      <option> ---- </option>
      <%@albums.each do |album|%>
        <option value="<%=album.id%>"> <%= album.title %></option>
      <%end%>
    </select>
  </label>

  <label>Title 
    <input type="text" name="track[title]"/>
  </label>

  <label>Track Number
    <input type="number" name="track[ord]"/>
  </label>

  <label>Track Type 
    <input
      type="radio"
      name="track[track_type]"
      value="Regular"
      id="reg_track" 
      checked/>
    <label for="reg_track">Regular</label>
    <input
      type="radio"
      name="track[track_type]"
      value="Bonus"
      id="bonus_track" />
    <label for="bonus_track">Bonus</label>
  </label>
  </br>
  <label>Lyrics
    <textarea name="track[lyrics]"></textarea>
  </label>
  <input type="submit" value="Submit the track">

</form>

W10D1/music_app/app/views/tracks/show.html.erb
<h1><%=@track.title%></h1>
<a href></a>
<div>
  <%=@track.lyrics%>
</div>
</br>
  <form action="<%= track_url %>" method="POST">
    <input type="hidden" name="_method" value="DELETE" />
    <input type="submit" value="Delele this track?">
  </form>
</br>
<a href="<%=album_url(@track.album.id)%>">back to <%=@track.album.title%>?</a>